In [2]:
import numpy as np
print (dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [10]:
arr1 = np.array([45,80,25.2,32],)
arr1

array([45. , 80. , 25.2, 32. ])

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr1.shape

(4,)

In [13]:
arr1.ndim

1

In [14]:
arr2=np.array([[98,56,54,25], [12,33,69,65],[45,48,12,14]])
arr2

array([[98, 56, 54, 25],
       [12, 33, 69, 65],
       [45, 48, 12, 14]])

In [17]:
arr2.dtype

dtype('int32')

In [15]:
arr2.shape

(3, 4)

In [16]:
arr2.ndim

2

In [18]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.ones((2,3))*15

array([[15., 15., 15.],
       [15., 15., 15.]])

In [28]:
np.zeros((4,5))+15

array([[15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.]])

In [29]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [36]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [37]:
np.linspace(14,50,100) #this generates a number between 14 to 50 where 100 is the total number of digits between 14 to 50 generated

array([14.        , 14.36363636, 14.72727273, 15.09090909, 15.45454545,
       15.81818182, 16.18181818, 16.54545455, 16.90909091, 17.27272727,
       17.63636364, 18.        , 18.36363636, 18.72727273, 19.09090909,
       19.45454545, 19.81818182, 20.18181818, 20.54545455, 20.90909091,
       21.27272727, 21.63636364, 22.        , 22.36363636, 22.72727273,
       23.09090909, 23.45454545, 23.81818182, 24.18181818, 24.54545455,
       24.90909091, 25.27272727, 25.63636364, 26.        , 26.36363636,
       26.72727273, 27.09090909, 27.45454545, 27.81818182, 28.18181818,
       28.54545455, 28.90909091, 29.27272727, 29.63636364, 30.        ,
       30.36363636, 30.72727273, 31.09090909, 31.45454545, 31.81818182,
       32.18181818, 32.54545455, 32.90909091, 33.27272727, 33.63636364,
       34.        , 34.36363636, 34.72727273, 35.09090909, 35.45454545,
       35.81818182, 36.18181818, 36.54545455, 36.90909091, 37.27272727,
       37.63636364, 38.        , 38.36363636, 38.72727273, 39.09

In [38]:
np.linspace(14,50)

array([14.        , 14.73469388, 15.46938776, 16.20408163, 16.93877551,
       17.67346939, 18.40816327, 19.14285714, 19.87755102, 20.6122449 ,
       21.34693878, 22.08163265, 22.81632653, 23.55102041, 24.28571429,
       25.02040816, 25.75510204, 26.48979592, 27.2244898 , 27.95918367,
       28.69387755, 29.42857143, 30.16326531, 30.89795918, 31.63265306,
       32.36734694, 33.10204082, 33.83673469, 34.57142857, 35.30612245,
       36.04081633, 36.7755102 , 37.51020408, 38.24489796, 38.97959184,
       39.71428571, 40.44897959, 41.18367347, 41.91836735, 42.65306122,
       43.3877551 , 44.12244898, 44.85714286, 45.59183673, 46.32653061,
       47.06122449, 47.79591837, 48.53061224, 49.26530612, 50.        ])

In [40]:
np.linspace(1,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [44]:
arr3=np.arange(1,151)
arr3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150])

In [48]:
arr3=np.arange(1,151 , step=3)
arr3

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100, 103, 106, 109, 112, 115,
       118, 121, 124, 127, 130, 133, 136, 139, 142, 145, 148])

In [50]:
arr3=np.arange(0,151 , step=2)
arr3

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [51]:
arr4=np.random.randint(10,75)
arr4

65

In [53]:
arr4=np.random.randint(10,75, size=100)
arr4

array([12, 18, 57, 49, 36, 41, 34, 46, 19, 30, 26, 12, 54, 72, 45, 38, 57,
       58, 25, 74, 55, 73, 34, 21, 52, 38, 37, 74, 13, 23, 54, 65, 74, 45,
       55, 30, 20, 57, 40, 38, 43, 56, 13, 64, 17, 35, 48, 34, 39, 58, 71,
       62, 16, 49, 63, 29, 52, 36, 25, 13, 16, 72, 60, 74, 13, 60, 27, 45,
       23, 37, 69, 43, 36, 58, 74, 52, 55, 60, 45, 55, 59, 71, 31, 44, 41,
       71, 33, 39, 72, 33, 25, 45, 58, 74, 73, 50, 57, 73, 22, 52])

In [56]:
arr4=np.random.randint(0,9, size=5)
arr4

array([5, 7, 4, 2, 3])

In [65]:
np.random.seed(4)
arr4=np.random.randint(10,75, size=100)
arr4

array([56, 65, 11, 60, 19, 68, 65, 65, 67, 46, 60, 54, 48, 62, 13, 10, 65,
       31, 31, 48, 66, 56, 40, 18, 59, 68, 42, 50, 52, 55, 43, 42, 38, 13,
       67, 60, 27, 69, 58, 33, 32, 72, 72, 33, 66, 65, 63, 46, 69, 61, 18,
       47, 69, 64, 40, 14, 64, 18, 41, 50, 27, 19, 63, 72, 69, 13, 14, 49,
       64, 50, 63, 32, 27, 37, 70, 53, 25, 23, 10, 20, 17, 73, 69, 62, 62,
       74, 56, 52, 59, 41, 45, 40, 13, 30, 17, 61, 20, 51, 25, 51])

In [66]:
arr5=arr4.reshape(10,10)
arr5

array([[56, 65, 11, 60, 19, 68, 65, 65, 67, 46],
       [60, 54, 48, 62, 13, 10, 65, 31, 31, 48],
       [66, 56, 40, 18, 59, 68, 42, 50, 52, 55],
       [43, 42, 38, 13, 67, 60, 27, 69, 58, 33],
       [32, 72, 72, 33, 66, 65, 63, 46, 69, 61],
       [18, 47, 69, 64, 40, 14, 64, 18, 41, 50],
       [27, 19, 63, 72, 69, 13, 14, 49, 64, 50],
       [63, 32, 27, 37, 70, 53, 25, 23, 10, 20],
       [17, 73, 69, 62, 62, 74, 56, 52, 59, 41],
       [45, 40, 13, 30, 17, 61, 20, 51, 25, 51]])

In [67]:
arr5[4,4]
#to select a particular number from the array we use the rows and coloumn to pick starting count from 0


66

In [71]:
#      [56, 65, 11, 60, 19, 68, 65, 65, 67, 46],
 #      [60, 54, 48, 62, 13, 10, 65, 31, 31, 48],
 #      [66, 56, 40, 18, 59, 68, 42, 50, 52, 55],
  #     [43, 42, 38, (13, 67, 60, 27,) 69, 58, 33],
   #    [32, 72, 72, (33, 66, 65, 63,) 46, 69, 61],
   #    [18, 47, 69, (64, 40, 14, 64,) 18, 41, 50],
    #   [27, 19, 63, (72, 69, 13, 14,) 49, 64, 50],
     #  [63, 32, 27, 37, 70, 53, 25, 23, 10, 20],
     #  [17, 73, 69, 62, 62, 74, 56, 52, 59, 41],
      # [45, 40, 13, 30, 17, 61, 20, 51, 25, 51]

arr5[3:7,3:7]
#to select a particular number from the array we use the rows and coloumn to pick starting count from 0


array([[13, 67, 60, 27],
       [33, 66, 65, 63],
       [64, 40, 14, 64],
       [72, 69, 13, 14]])

In [72]:
arr6=arr5.flatten()
arr6
#to convert a 2d back to 1 dimension

array([56, 65, 11, 60, 19, 68, 65, 65, 67, 46, 60, 54, 48, 62, 13, 10, 65,
       31, 31, 48, 66, 56, 40, 18, 59, 68, 42, 50, 52, 55, 43, 42, 38, 13,
       67, 60, 27, 69, 58, 33, 32, 72, 72, 33, 66, 65, 63, 46, 69, 61, 18,
       47, 69, 64, 40, 14, 64, 18, 41, 50, 27, 19, 63, 72, 69, 13, 14, 49,
       64, 50, 63, 32, 27, 37, 70, 53, 25, 23, 10, 20, 17, 73, 69, 62, 62,
       74, 56, 52, 59, 41, 45, 40, 13, 30, 17, 61, 20, 51, 25, 51])

In [73]:
np.sum(arr6)

4622

In [74]:
np.mean(arr6)

46.22

In [75]:
np.median(arr6)

50.0

In [76]:
np.min(arr6)

10

In [77]:
np.max(arr6)

74

In [78]:
np.var(arr6)

373.6116

In [81]:
np.std(arr6)

19.329035154399197

In [82]:
np.percentile(arr6,45)

47.550000000000004

In [84]:
np.sqrt(arr6)

array([7.48331477, 8.06225775, 3.31662479, 7.74596669, 4.35889894,
       8.24621125, 8.06225775, 8.06225775, 8.18535277, 6.78232998,
       7.74596669, 7.34846923, 6.92820323, 7.87400787, 3.60555128,
       3.16227766, 8.06225775, 5.56776436, 5.56776436, 6.92820323,
       8.1240384 , 7.48331477, 6.32455532, 4.24264069, 7.68114575,
       8.24621125, 6.4807407 , 7.07106781, 7.21110255, 7.41619849,
       6.55743852, 6.4807407 , 6.164414  , 3.60555128, 8.18535277,
       7.74596669, 5.19615242, 8.30662386, 7.61577311, 5.74456265,
       5.65685425, 8.48528137, 8.48528137, 5.74456265, 8.1240384 ,
       8.06225775, 7.93725393, 6.78232998, 8.30662386, 7.81024968,
       4.24264069, 6.8556546 , 8.30662386, 8.        , 6.32455532,
       3.74165739, 8.        , 4.24264069, 6.40312424, 7.07106781,
       5.19615242, 4.35889894, 7.93725393, 8.48528137, 8.30662386,
       3.60555128, 3.74165739, 7.        , 8.        , 7.07106781,
       7.93725393, 5.65685425, 5.19615242, 6.08276253, 8.36660

In [86]:
#exercise 
#generate an array between 4,80,150 in total 
#convert the array to 2d of the nearest rows and colomns
# after select the values from row 3 to 6 and colomn 4 to 7
# find the sum, max,min,std, 30 percentile, 75 percentile , mena and var of the array

In [88]:
#sol

In [93]:
arr8=np.random.randint(4,80, size=150)
arr8

array([32, 45,  5, 47, 58, 31, 52, 22, 60, 16, 77, 20, 46, 69, 41, 73, 27,
       48, 46, 47, 26, 60, 49, 71, 74, 14, 14, 40, 38, 12, 62, 75, 42,  6,
       66, 76, 38, 53, 52, 43, 29, 20, 54, 32, 20,  4, 17, 28, 26, 40, 45,
       28, 20, 78, 24, 37, 47, 25, 39, 65, 61, 71,  5, 41, 27, 27, 60, 17,
        5, 64, 26, 50, 33, 20,  4, 32, 77, 77,  8, 25, 45, 44, 36,  4, 43,
       18, 32, 49, 64, 46, 30, 18, 68, 64, 36, 67, 10, 42, 13, 41, 38, 49,
       64, 28, 72,  9, 25, 23, 66, 50, 13, 59, 48, 68, 51, 49,  5, 61, 37,
       44, 67,  8,  8, 10, 22, 44, 65, 18,  5, 34,  6, 56, 20, 18, 11, 27,
       61, 19, 36, 64, 16, 29, 21, 77, 79, 63,  4, 23, 55, 20])

In [94]:
arr9=arr8.reshape(10,15)
arr9

array([[32, 45,  5, 47, 58, 31, 52, 22, 60, 16, 77, 20, 46, 69, 41],
       [73, 27, 48, 46, 47, 26, 60, 49, 71, 74, 14, 14, 40, 38, 12],
       [62, 75, 42,  6, 66, 76, 38, 53, 52, 43, 29, 20, 54, 32, 20],
       [ 4, 17, 28, 26, 40, 45, 28, 20, 78, 24, 37, 47, 25, 39, 65],
       [61, 71,  5, 41, 27, 27, 60, 17,  5, 64, 26, 50, 33, 20,  4],
       [32, 77, 77,  8, 25, 45, 44, 36,  4, 43, 18, 32, 49, 64, 46],
       [30, 18, 68, 64, 36, 67, 10, 42, 13, 41, 38, 49, 64, 28, 72],
       [ 9, 25, 23, 66, 50, 13, 59, 48, 68, 51, 49,  5, 61, 37, 44],
       [67,  8,  8, 10, 22, 44, 65, 18,  5, 34,  6, 56, 20, 18, 11],
       [27, 61, 19, 36, 64, 16, 29, 21, 77, 79, 63,  4, 23, 55, 20]])

In [95]:
arr5[3:6,4:7]

array([[67, 60, 27],
       [66, 65, 63],
       [40, 14, 64]])

In [96]:
np.sum(arr9)

5796

In [97]:
np.max(arr9)

79

In [98]:
np.min(arr9)

4

In [99]:
np.std(arr9)

21.30611179919978

In [100]:
np.percentile(arr9 , 30)

24.699999999999996

In [101]:
np.percentile(arr9, 75)

55.75

In [102]:
np.mean(arr9)

38.64

In [103]:
np.var(arr9)

453.95040000000006

In [1]:






#day 18 data science python propal

In [2]:
import numpy as np
import pandas as pd

In [5]:
cols = [ 'CA1', 'CA2', 'CA3']
sitno = np.arange(1,51)
np.random.seed(5)
score = np.random.randint(1,11,150)
score = score.reshape(50,3)
df =pd.DataFrame(data =score, index= sitno, columns=cols)
df

CA1  CA2  CA3
1     4    7    7
2     1   10    9
3     5    8    1
4     1    8    2
5     6    8    1
6     2    5    7
7     3   10   10
8    10   10    2
9     3    8    1
10    6    1    1
11    5    5   10
12    4    3    5
13    7   10    4
14    4    3    2
15    6    8    5
16    4    2    8
17    4    2   10
18    6    8    1
19   10    7    1
20    6    3    9
21    7    9    1
22    6    3    1
23    8    8    7
24    1    1    9
25    6    6   10
26    7    5    6
27    3    9    9
28    2    7    4
29    5    2    9
30    1    3    3
31    5    2    7
32    4    5    4
33    2    5    3
34    4    5   10
35    5    1    7
36    7   10    3
37   10    4    1
38    9    9   10
39    8    5    9
40    7    9    1
41    6    4    5
42    1    3    3
43    2    2    8
44    2    8    3
45    7    4    7
46    9    1   10
47    2   10    1
48    9    8    8
49   10    5    2
50    5    3    2